# env.py
MERAKI_CLIENT_ID = "YOUR_CLIENT_ID"
MERAKI_CLIENT_SECRET = "YOUR_SECRET_HERE"
MERAKI_REDIRECT_URI = "http://localhost:8080/callback"
MERAKI_REFRESH_TOKEN_PATH = "tokens/refresh_token.json"
MERAKI_ORG_ID = "YOUR_ORG_ID"
